Train:
  num_step: 50
  batch_size: 256
  learning_rate: 0.01
  embed_size: 100
  num_hiddens: 200
  epochs: 15
  save_best: True
  trainer: "Adam"
  loss: "CrossEntropyLoss"
  train_data: "contract_nli/data/train.csv"
  test_data: "contract_nli/data/test.csv"
